<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121113090935 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE account CHANGE site site INT NOT NULL");
        $this->addSql("ALTER TABLE log ADD user INT DEFAULT NULL");
        $this->addSql("ALTER TABLE log ADD CONSTRAINT FK_8F3F68C58D93D649 FOREIGN KEY (user) REFERENCES fos_user_user (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_8F3F68C58D93D649 ON log (user)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE account CHANGE site site INT DEFAULT NULL");
        $this->addSql("ALTER TABLE log DROP FOREIGN KEY FK_8F3F68C58D93D649");
        $this->addSql("DROP INDEX IDX_8F3F68C58D93D649 ON log");
        $this->addSql("ALTER TABLE log DROP user");
    }
}
