<?php

namespace Lacus\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MapperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapperRepository extends EntityRepository
{
}
