<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var \Lacus\MainBundle\Entity\Site[]
     */
    protected $sites;

    /**
     * @var \Lacus\MainBundle\Entity\Post[]
     */
    protected $posts;

    /**
     * @var \Lacus\MainBundle\Entity\Log[]
     */
    protected $logs;


    public function __construct()
    {
        parent::__construct();
        $this->sites = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->logs = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \Lacus\MainBundle\Entity\Site[]
     */
    public function getSites()
    {
        return $this->sites;
    }

    /**
     * @param ArrayCollection $sites
     */
    public function setSites(ArrayCollection $sites)
    {
        /** @var $sites \Lacus\MainBundle\Entity\Site[] */
        /** @var $newSites \Lacus\MainBundle\Entity\Site[] */
        $existingSites = $this->getSites();
        $newSites = array();
        foreach ($sites as $site) {
            if (!isset($existingSites[$site->getId()])) {
                $site->addUser($this);
            }
            $newSites[$site->getId()] = $site;
        }
        foreach ($existingSites as $site) {
            if (!isset($newSites[$site->getId()])) {
                $site->removeUser($this);
            }
        }
        $this->setUpdatedAt(new \DateTime());
        $this->sites = $newSites;
    }

    public function getLogs()
    {
        return $this->logs;
    }

    public function setLogs($logs)
    {
        $this->logs = $logs;
    }
}